apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dep-proc
spec:
  replicas: 2
  selector:
    matchLabels:
      fardeen: attar
  template:
    metadata:
      labels:
        fardeen: attar
    spec:
      containers:
        - name: custom-container
          image: fardeenattar/tomacat
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-svc 
  labels: 
    fardeen: attar
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080 
      protocol: TCP 
  selector:
    fardeen: attar
          
