apiVersion: autoscaling/v2
kind: HorizontalPodAutoScaler
metadata:
  name: my-asg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dep-proc
  minReplicas:
  maxReplicas:
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 1
